targets:
  $default:
    builders:
      gql_gen|graphql_string_builder:
        generate_for:
          - lib/**.graphql
          - lib/**/*.graphql
      gql_gen|graphql_aggregate_builder: {}

builders:
  graphql_string_builder:
    import: "package:gql_gen/src/graphql_builder.dart"
    builder_factories: ["graphQLStringBuilder"]
    build_extensions: { ".graphql": [".graphql.dart"] }
    auto_apply: dependents
    build_to: source
    defaults:
      options:
        # Optional: one of 'embed' (default) or 'load'.
        mode: embed
        # Optional: include globs to limit processing
        include: ["lib/graphql/**/*.graphql"]
        # Optional: exclude globs
        exclude: []

  graphql_aggregate_builder:
    import: "package:gql_gen/src/aggregate_builder.dart"
    builder_factories: ["graphQLAggregateBuilder"]
    build_extensions: { "$lib$": ["graphql/generatedOutputs/Queries.dart"] }
    auto_apply: dependents
    build_to: source
    defaults:
      options:
        # Optional: one of 'embed' (default) or 'load'.
        mode: embed
        include: ["lib/graphql/**/*.graphql"]
        exclude: []
